---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: copy file from ansible-master to node
      copy: 
        src: /root/ansible/testfile.txt
        dest: /root/testfile.txt
        remote_src: yes
       
